[package]
name = "ftkit"
version = "0.1.4"
edition = "2021"
authors = ["Nils Mathieu <nmathieu@student.42.fr>"]
description = "A small set of utilities for newcomers learning Rust."
license-file = "LICENSE.md"

[dependencies]
getrandom = "0.2"
