[package]
name = "ftkit"
version = "0.1.5"
edition = "2021"
authors = ["Nils Mathieu <nmathieu@student.42.fr>"]
description = "A small set of utilities for newcomers learning Rust."
license-file = "LICENSE.md"
readme = "README.md"

[dependencies]
getrandom = "0.2"
