[package]
name = "nls"
version = "0.1.4"
edition = "2021"
authors = ["Nils Mathieu <nils.mathieu.contact@gmail.com>"]
description = "A small set of utilities for newcomers learning Rust."
license-file = "LICENSE.md"

[dependencies]
getrandom = "0.2"
